[project]
name = "auth-services"
version = "0.1.0"
requires-python = ">3.12"
dependencies = [
    "fastapi[standard]",
    "httpx",
    "python-multipart",
    "uvicorn[standard]",
]

[tool.pytest.ini_options]
testpaths = ["tests"]
addopts = ["--import-mode=prepend"]

[tool.ruff]
line-length = 88
